### ISSUE TITLE
perceptron in chapter1 never outputs 0

### ISSUE THREAD

**Issue by msapaydin** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#10]
this is due to using np.random.rand which outputs always positive numbers.

**Comment by msapaydin** [comment]
instead randn may be used.

**Comment by benjaminplanche** [comment]
Hello @msapaydin,

Thank you very much for your valid remark!
It is true that, as it is, the `Neuron` instance would unlikely output `0` because of the simplistic way its weights are initialized. This is actually one of the implicit reasons why the readers are invited to "_edit the weights_" (text before cell 36 in [Notebook 1.1](https://github.com/PacktPublishing/Hands-On-Computer-Vision-with-TensorFlow-2/blob/b3d9f81af180a75f5d3a627be6fe2e5ee08f6bee/Chapter01/ch1_nb1_build_and_train_neural_network_from_scratch.ipynb)).

Note that, as you suggest, the more proper `numpy.random.standard_normal()` (function similar to `numpy.random.randn()`) is actually used afterwards to initialize the weights of `FullyConnectedLayer`, for the rest of the notebook.

I hope this has been of some help.

**Comment by msapaydin** [comment]
Hi @benjaminplanche , the `Neuron` instance never outputs 0. I indeed tried to edit the weights and never got a 0 out of the perceptron, and had to look up the reason. Thanks.

**Comment by benjaminplanche** [comment]
Hello @msapaydin,

Have you tried manually editing the weights' values? (e.g., entering something like `perceptron.W = np.asarray([-.5, .1, -.7])`). As you inferred yourself I believe, the result of the linear operation (`W . x + b`) should be negative or null for the perceptron's step function to return `0`. This means that either some of the weights should be negative (if we consider the values of `x` positive), or all the weights should be `0` (which is _possible_ with `numpy.random.rand()`, though highly unlikely).

To tell the truth, we were expecting people not to spend much time on this 1st exercise (the rest of the chapter does not depend on this code), or that more curious people would figure out how to get `0` if they want. It was probably an oversight. Therefore, following your suggestion, I've clarified the code a bit (so that `0` can be likely obtained without manual edits). Thank you!

**Comment by msapaydin** [comment]
No problem. I was teaching based on this material and thought I should let
you know about this minor issue. Best wishes.

--MSA

**Comment by benjaminplanche** [comment]
Thank you again! Closing this issue then. :)
