### ISSUE TITLE
Unable to prepare cityscape-dataset

### ISSUE THREAD

**Issue by GaryKuo368** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#22]
Hi,
I have the same issue as previous "Unable to prepare cityscape-dataset #8" on Jun 29, 2019.

I  have verified the environment has been se by:
import os
print(os.environ['CITYSCAPES_DATASET'])
it retuned
C:\Users\c5911\tensorflow_datasets\cityscapes.

However, two scripts
!csCreateTrainIdLabelImgs
or
!csViewer (ran under Jupyter notebook)
still returned:
ERROR: Did not find any files. Please consult the README.

I ran csViewer at prompt command, it also showed "The data was not found".

Under "C:\Users\c5911\tensorflow_datasets\cityscapes", there are two sub folders, getFine and leftImg8bit.

Anything could be wrong?

Thanks.

**Comment by benjaminplanche** [comment]
Hi @GaryKuo368,

Sorry you are encountering some issues. 
Since your problem seems to come from the `cityscapesScripts` library, I would suggest to share your issue there to get better insight ([`cityscapesScripts` issue page](https://github.com/mcordts/cityscapesScripts/issues)). Maybe this thread there could help you: ["can't use cityScapesViewer.py `#20`"](https://github.com/mcordts/cityscapesScripts/issues/20).

The only insight I could provide would be to double-check that your path variable is properly set and that your dataset folder contains all the expected data in the correct format.
For example, you could manually check the paths, the same way as `cityScapesViewer` (c.f. this [function](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/viewer/cityscapesViewer.py#L1339) that likely throws the "data not found" error that you mentioned). For example, checking in such a way:


```python
import os
from glob import glob

cs_path = os.environ['CITYSCAPES_DATASET']
print("Path - CITYSCAPES_DATASET = {}".format(cs_path))

# c.f. https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/viewer/cityscapesViewer.py#L1350
splits = ["train_extra", "train", "val", "test"]
for split in splits:
    cities = glob(os.path.join(cs_path, "leftImg8bit", split, '*'))
    print("Split {} - cities found = {}.".format(split, len(cities)))

# c.f. https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py#L38
searchFine = os.path.join(cs_path , "gtFine"   , "*" , "*" , "*_gt*_polygons.json" )
searchCoarse = os.path.join(cs_path , "gtCoarse" , "*" , "*" , "*_gt*_polygons.json" )
filesFine = glob( searchFine )
filesCoarse = glob.glob( searchCoarse )
print("GT (fine) - files found = {}.".format(len(filesFine)))
print("GT (coarse) - files found = {}.".format(len(filesCoarse)))
```

Hopefully this could help you figure if/which data is missing, or if the problem comes from elsewhere.

**Comment by GaryKuo368** [comment]
Thanks.

I tried your code:
Output was:
Path - CITYSCAPES_DATASET = C:\Users\c5911\datasets\cityscapes
Split train_extra - cities found = 0.
Split train - cities found = 0.
Split val - cities found = 0.
Split test - cities found = 0.
GT (fine) - files found = 0.
GT (coarse) - files found = 0.

The cityscapes data I downloaded dose include different city folder under both gtFine and leftImg8bit subfolders. It dose not include "gtCoarse" subfolder. There is no train_extra under both gtFine and leftImg8bit.

Anything wrong in my dataset?

Thanks.

![CityScapes](https://user-images.githubusercontent.com/61132018/128659944-2d21ad96-a247-4f84-b4f1-6bf1f14b5dd7.PNG)

**Comment by benjaminplanche** [comment]
Hi @GaryKuo368,

Your folder structure should be `C:\Users\c5911\tensorflow_datasets\cityscapes\leftImg8bit`, not `C:\Users\c5911\tensorflow_datasets\cityscapes\leftImg8bit\leftImg8bit` (notice the extra `leftImg8bit` in your case). I suspect the problem is the same for the GT folders.

If you manually unzip the archive, be careful to choose "_Extract here_", instead of "_Extract into folder ..._" ; I assume this is how you ended up with the extra folder layers.

From your screenshot, it appears that you unzipped the
