### ISSUE TITLE
Ch6. nb5 build and train: fcn8s_model.fit, ValueError: Shapes (None, 512, 512, 19) and (None, 512, 512, 1) are incompatible

### ISSUE THREAD

**Issue by GaryKuo368** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#23]
Hi
I am running ch6. nb5 build and train.
At fcn8s_model.fit, I have a ValueError: Shapes (None, 512, 512, 19) and (None, 512, 512, 1) are incompatible (after "C:\Users\c5911\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))").
fcn8s_model.summary() showed 
conv2d_transpose_2 (Conv2DTrans (None, 512, 512, 19) 92435       add_1[0][0]                      
==================================================================================================
Total params: 14,983,177
Trainable params: 14,983,177
Non-trainable params: 0

Why were there incompatible shape? 

Thanks,
Gary

P.S.: I changed: visual_val_dataset = cityscapes_input_fn(
    root_folder=CITYSCAPES_FOLDER, resize_to=image_size, batch_size=num_show,
    shuffle=True, num_epochs=1, augment=False, seed=random_seed, blurred=False) #blurred changed from "True" to "False".

**Comment by benjaminplanche** [comment]
Hello @GaryKuo368,

Could you please provide the full trace? In order to understand the issue, it would be important to know the names of the 2 incompatible tensors. Also, have you made any other changes to the code (network architecture, loss or metrics, callbacks)?

For examples, it seems to me that something changed in your network architecture, since it has much less trainable parameters than expected (14,983,177, versus 134,124,094 c.f. [cell 10 in the online notebook 6.5](https://nbviewer.jupyter.org/github/PacktPublishing/Hands-On-Computer-Vision-with-TensorFlow-2/blob/master/Chapter06/ch6_nb5_build_and_train_a_fcn8s_semantic_segmentation_model_for_smart_cars.ipynb)). This may or may not be related to your issue (the full trace would help determine this).

Thank you!

P.S.: The parameter `blurred` of the function `cityscapes_input_fn` is actually set to `False` by default (c.f. [cityscapes_utils.py#L218](https://github.com/PacktPublishing/Hands-On-Computer-Vision-with-TensorFlow-2/blob/e0d91c1aeadd7558de920583094c05f840b700a9/Chapter06/cityscapes_utils.py#L218)). This should not be related to your issue.
