### ISSUE TITLE
Unable to prepare cityscape-dataset

### ISSUE THREAD

**Issue by catweis** [PacktPublishing/Hands-On-Computer-Vision-with-Tensorflow#8]
Hi,

running the script (Mac, Jupyter-notebook, Python 2), I am unable to prepare the dataset.
There is the message "ERROR: Did not find any files. Please consult the README.", which I can not interpret.
Running the script step by step on the terminal, there is the same problem.
Has anyone an idea how to solve this?

Searching the internet, I only found this link:
https://github.com/mcordts/cityscapesScripts/issues/73
However, their solution does not work for me.

Unfortunately, without this data, I can not further work on the chapter of this nice book.

With kind regards

**Comment by benjaminplanche** [comment]
Hi @catweis, 
Sorry you're encountering this problem.

Could you provide a bit more context, e.g., which operation/command is causing the error message you mentioned?
Have you provided the `cityscapesscripts` module with the proper path to where you unzipped the dataset? (c.f. the `export CITYSCAPES_DATASET=...` command in [Installation section, cell 2](https://render.githubusercontent.com/view/ipynb?commit=e33fa287d1320dac09703d14bbc940fb686de810&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f5061636b745075626c697368696e672f48616e64732d4f6e2d436f6d70757465722d566973696f6e2d776974682d54656e736f72466c6f772d322f653333666132383764313332306461633039373033643134626263393430666236383664653831302f4368617074657230362f6368365f6e62345f707265706172696e675f646174615f666f725f736d6172745f6361725f617070732e6970796e62&nwo=PacktPublishing%2FHands-On-Computer-Vision-with-TensorFlow-2&path=Chapter06%2Fch6_nb4_preparing_data_for_smart_car_apps.ipynb&repository_id=151050847&repository_type=Repository#Installation))

All the best.

**Comment by catweis** [comment]
Dear Sir,

thank you very much for the fast and friendly answer to my problem.
First of all, I really like your book and it is for me - switching from machine learning in Matlab to Python - a great help!
However, with this background, my problem could be a very basic issue.

Regarding the context:
I downloaded the cityscapes data into one folder, as described in the script. Then, I provided my cityscapes path in your script. 

# Uncomment below to execute from notebook:
!export CITYSCAPES_DATASET="/Users/cleo-aronweis1/Hands-On-Computer-Vision-with-TensorFlow-2/cityscapesDataSet"

Then, I have downloaded the git-repository (by !git clone https://github.com/mcordts/cityscapesScripts.git) in this directory.
In the next step, the error occurs:

!csCreateTrainIdLabelImgs
ERROR: Did not find any files. Please consult the README

One problem was that I am working with anaconda and environments. Therefore, I had to run the code from python on the terminal in the environment and not from the jupyter notebook.
With “!” before a command, it does not work. 
But again, this error occurs. 
In the README, I was not able to find the solution. In the internet, some people describe to change the cityscapes-script (https://github.com/mcordts/cityscapesScripts/issues/73 <https://github.com/mcordts/cityscapesScripts/issues/73>); however, that does also not help.

Thank you very much in advance for your thoughts concerning this point.

With kind regards

**Comment by benjaminplanche** [comment]
Dear @catweis,

I am glad the book has been useful so far! Thank you also for the details regarding your issue.

It seems to me like either the variable `CITYSCAPES_DATASET` pointing to the dataset folder has not been properly set, or the path is not correct (though it may be another error -- I alas do not have access to a Mac system to reproduce the problem).

Could you make sure that the path you assigned to the variable (i.e., `/Users/cleo-aronweis1/Hands-On-Computer-Vision-with-TensorFlow-2/cityscapesDataSet` in your case) contains the unzipped dataset? This folder should contain at least 2 sub-folders named `gtFine/` and `leftImg8bit/` with the data samples in.

Otherwise, could you double-check that the environment variable has been properly set? E.g. by entering the following command in Python and checking that the value correspond to your path:

    import os
    print(os.environ['CITYSCAPES_DATASET'])

Regarding your other comments:
- You are right, the "`!`" should be removed before the commands, if you are not executing them inside the notebooks (these symbols are meant for Jupyter Notebook, so it knows those are system commands, not Python ones).
- If it can somehow useful to you, please note that you can also use Jupyter Notebook with Anaconda and personal environments. Instructions are provided in the Anaconda documentation, e.g. here: [Anaconda Doc - Working with environments](https://docs.anaconda.com/ae-notebooks/user-guide/adv-tasks/work-with-environments/).

Please let me know if this was of any help.
All the best.
